export const UserEntity = {
    name: "User",
    description: "User details",
    is_default: true,
    field: [{
        name: "firstname",
        type_name: "Text",
        data_type: "String",
        description: "user first name",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    },
    {
        name: "lastname",
        type_name: "Text",
        data_type: "String",
        description: "user last name",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    },
    {
        name: "username",
        type_name: "Text",
        data_type: "String",
        description: "username",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "email",
        type_name: "Text",
        data_type: "String",
        description: "user Email",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "password",
        type_name: "Text",
        data_type: "String",
        description: "user password",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "phonenumber",
        type_name: "Text",
        data_type: "String",
        description: "user phone number",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "Idtoken",
        type_name: "Text",
        data_type: "String",
        description: "Jwt token of user details",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "loggedinDate",
        type_name: "Text",
        data_type: "Date",
        description: "user Logged in date",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "loggedoutDate",
        type_name: "Text",
        data_type: "Date",
        description: "user Logged out date",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "role",
        type_name: "Text",
        data_type: "{ type: mongoose.Schema.Types.String, ref: 'roles' }",
        description: "Role of the User",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    }, {
        name: "org",
        type_name: "Text",
        data_type: "String",
        description: "Organization name",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    },
    {
        name: "org_country",
        type_name: "Text",
        data_type: "String",
        description: "Country of the organization",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    },
    {
        name: "org_sub1",
        type_name: "Text",
        data_type: "String",
        description: "Sub organization one",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    },
    {
        name: "org_sub2",
        type_name: "Text",
        data_type: "String",
        description: "Sub organization two",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    },
    {
        name: "org_sub3",
        type_name: "Text",
        data_type: "String",
        description: "Sub organization three",
        is_default: true,
        is_entity_type: false,
        is_list_type: false,
        list_type: null,
        list_value: null,
        entity_id: null,
    },
    ]
}